version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
  backend:
    build: ./server
    ports:
      - 5000:5000
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017

volumes:
  myapp:
